name: CalledWorkflow

on:
 repository_dispatch:
    types: [CalledWorkflow]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
       parameter1: ${{ github.event.client_payload.parameter1 }}
       parameter2: ${{ github.event.client_payload.parameter2 }}

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Cloud Quick Labs!

      - name: Write data to file
      - uses: DamianReeves/write-file-action@master
        with:
          path: ${{ $GITHUB_WORKSPACE }}/param.txt
           contents:|
                   echo $parameter1
                   echo $parameter2
           write-mode:append
        
