name: CalledWorkflow

on:
 repository_dispatch:
    types: [CalledWorkflow]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
       parameter1: ${{ github.event.client_payload.parameter1 }}
       parameter2: ${{ github.event.client_payload.parameter2 }}

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Cloud Quick Labs!

      - name: Output param values
        run: |
          echo $parameter1
          echo $parameter2
          
      - uses: actions/checkout@v4
      - run: |
          echo $parameter1 >> param.txt
          echo $parameter2 >> param.txt
          date >> param.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "param"
          git push
